services:
  streamlit:
    build: .
    image: "streamlit-chat-gpt"
    container_name: "streamlit-chat-gpt"
    env_file:
     - .env
    ports:          
      - "8501:8501"
    tty: true
    stdin_open: true
